language: node_js

node_js:
  - "12"

cache:
  directories:
    - "build"
    - "coverage"
    - "node_modules"
    - "$HOME/.sonar/cache"

stages:
  - setup
  - audit-lint-coverage
  - sonar
  - build
  - deploy

jobs:
  include:
    - stage: setup
      script:
        - npm i

    - stage: audit-lint-coverage
      script: npm audit
      name: audit
    - script: npm run lint
      name: lint
    - script: npm run coverage
      name: coverage

    - stage: sonar
      script: sonar-scanner
      name: sonar
      addons:
        sonarcloud:
          organization: "skaleb"
          token: "$SONAR_API_KEY"

    - stage: build
      script:
        - npm run build

    - stage: deploy
      deploy:
        provider: heroku
        api_key: "$HEROKU_API_KEY"
        app: "inhumanity-backend-service"
        skip_cleanup: true
